//> using scala 3.9.0
//> using dep org.typelevel::laika-core:1.3.2
//> using dep org.typelevel::laika-io:1.3.2

/*
 * Copyright 2026 Salar Rahmanian
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import laika.api.*
import laika.format.*
import laika.io.api.*
import laika.io.syntax.*
import laika.theme.*
import cats.effect.*
import laika.ast.Path.Root
import laika.config.LinkValidation
import laika.config.SyntaxHighlighting
import laika.helium.Helium
import laika.helium.config.*

/** Renders `docs/` into `site/target/docs/site`.
  *
  * This is the *only* place the site is rendered. `mill docs.preview` serves
  * this script's output rather than re-rendering with its own transformer —
  * two copies of the theme config had drifted before, and that is how syntax
  * highlighting ended up working in `docs.build` but not in the preview.
  */
object LaikaBuild extends IOApp.Simple {

  def run: IO[Unit] = for {
    _ <- IO.println("Starting Laika documentation build...")

    heliumTheme = Helium.defaults
      .all.metadata(
        title = Some("Verdict4s"),
        language = Some("en")
      )
      .site.topNavigationBar(
        homeLink = IconLink.internal(Root / "index.md", HeliumIcon.home),
        navLinks = Seq(
          // An ordinary page, so the link is validated. It is the page that
          // links on into each module's scaladoc under api/.
          TextLink.internal(Root / "api-reference.md", "API"),
          IconLink.external("https://github.com/softinio/verdict4s", HeliumIcon.github)
        )
      )
      .site.mainNavigation(depth = 3)
      .site.footer(
        """Verdict4s is a <a href="https://www.scala-lang.org">Scala 3</a> library.
          |Documentation built with <a href="https://typelevel.org/Laika/">Laika</a>.
          |""".stripMargin
      )
      .build

    transformer = Transformer
      .from(Markdown)
      .to(HTML)
      // GitHubFlavor only adds GFM parsing (tables, strikethrough, fenced
      // blocks). Highlighting is a separate opt-in bundle; without it, fenced
      // code renders as bare <pre><code> and Helium's CSS has no tokens to
      // colour.
      .using(Markdown.GitHubFlavor, SyntaxHighlighting)
      // The API reference under /api is generated by scaladoc, not by Laika,
      // so Laika cannot see those files; validate every link except those.
      .withConfigValue(LinkValidation.Global(excluded = Seq(Root / "api")))
      .parallel[IO]
      .withTheme(heliumTheme)
      .build

    _ <- IO.println("Running transformation...")
    _ <- transformer.use { t =>
      t.fromDirectory("docs")
        .toDirectory("site/target/docs/site")
        .transform
    }

    _ <- IO.println("Documentation site built successfully!")
  } yield ()
}
